################################################################################
# FILE: roles/qnap_stream_watcher/tasks/main.yml
################################################################################
---
- name: Include script-push tasks
  ansible.builtin.include_tasks: push_script.yml
