# FILE: playbooks/day0-prep-netboot.yml
---
- name: Prepare NFS-bootable root filesystem and kernel for Raspberry Pi 5 nodes
  hosts: k8smaster
  become: true
  gather_facts: true 
  tags:
    - netboot_day1

  vars_files:
    - variables/play/day1-prep-netboot.yml

  pre_tasks:
    - name: Ensure prerequisite configuration is applied
      import_role:
        name: prep-prerequisites

    - name: Install required base software packages
      import_role:
        name: install-required-software

    - name: Setup and configure NFS server
      import_role:
        name: setup-nfs-server

  tasks:
    - name: Create Raspberry Pi OS (Debian) root filesystem
      import_role:
        name: prep-rootfs

    - name: Install Raspberry Pi kernel and build/init stage for netboot
      import_role:
        name: prep-kernel

    - name: Publish kernel/initrd and rootfs to NFS/HTTP exports
      import_role:
        name: publish-nfs-os
